809 create poi
SanDiegoCountySheriff/VirtualCommandPostFE pull request #4
Opened 2021-06-26 00:36 UTC by Kai-ros

The route needs to be fixed, otherwise everything is in working order.

2021-06-27 16:49 UTC, Kai-ros commented
Getting a 400 Bad Request error with this route:
![image](https://user-images.githubusercontent.com/27451904/123552831-e5de0e00-d72c-11eb-9430-19d3ca3cb560.png)

2021-06-29 07:16 UTC, Kai-ros commented on src/components/POI/POI.tsx
> +        var time = new Date();
Need to use let as above, var shouldn't be used.

2021-06-29 07:16 UTC, Kai-ros commented on src/API/Contracts.ts
> +
Remove this extra line please.

2021-06-30 16:58 UTC, samlislalom approved these changes

2021-06-30 17:05 UTC, SlalomMarc commented on src/API/Contracts.ts
>      CreatedBy?: {
Not sure why CreatedBy is nullable.  We always need to know who created items in this.

2021-06-30 17:07 UTC, SlalomMarc commented on src/API/Endpoints.ts
> +const baseRoute = 'https://sdcs-vcp-api-dev.azurewebsites.net/api/';
These values should be in some kind of configuration so SDCS Build Pipelines will deploy properly.  (this URL is the Slalom Development Sandbox URL and SDCS will not be using that)

2021-06-30 17:08 UTC, SlalomMarc requested changes
Couple of minor-ish things to look at here.  Definitely not nits.

2021-07-01 22:10 UTC, merged